// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoiG-Ht5k3EAynbhhNkXao3bQEMfhlp-Y',
    appId: '1:269093119287:web:e882de94fa2d6f911326b2',
    messagingSenderId: '269093119287',
    projectId: 'ruh-fyp-railway-verify-app',
    authDomain: 'ruh-fyp-railway-verify-app.firebaseapp.com',
    storageBucket: 'ruh-fyp-railway-verify-app.firebasestorage.app',
    measurementId: 'G-969FZ3RR5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISmVKyzSfiNWO3-p7cPzqGmu8K8kREao',
    appId: '1:269093119287:android:a1e9b4cb17f035701326b2',
    messagingSenderId: '269093119287',
    projectId: 'ruh-fyp-railway-verify-app',
    storageBucket: 'ruh-fyp-railway-verify-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZhSwsFbY3REB2_jMJwj27GJt2p0NRYKo',
    appId: '1:269093119287:ios:c4e169137c2f757c1326b2',
    messagingSenderId: '269093119287',
    projectId: 'ruh-fyp-railway-verify-app',
    storageBucket: 'ruh-fyp-railway-verify-app.firebasestorage.app',
    iosBundleId: 'com.example.ruhFypRailwayTicketVerificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZhSwsFbY3REB2_jMJwj27GJt2p0NRYKo',
    appId: '1:269093119287:ios:c4e169137c2f757c1326b2',
    messagingSenderId: '269093119287',
    projectId: 'ruh-fyp-railway-verify-app',
    storageBucket: 'ruh-fyp-railway-verify-app.firebasestorage.app',
    iosBundleId: 'com.example.ruhFypRailwayTicketVerificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoiG-Ht5k3EAynbhhNkXao3bQEMfhlp-Y',
    appId: '1:269093119287:web:1693d4d9e08a86541326b2',
    messagingSenderId: '269093119287',
    projectId: 'ruh-fyp-railway-verify-app',
    authDomain: 'ruh-fyp-railway-verify-app.firebaseapp.com',
    storageBucket: 'ruh-fyp-railway-verify-app.firebasestorage.app',
    measurementId: 'G-9CDEEESP0B',
  );
}
